---
name: Update Wave Formula
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *  # hourly check
  repository_dispatch:
    types: [wave-release]
permissions:
  contents: write
  pull-requests: write
jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repo
        uses: actions/checkout@v4
      - name: Fetch latest release info
        id: get_release
        run: |
          RELEASE_JSON=$(curl -s https://api.github.com/repos/make-wave/wave/releases/latest)
          URL_ARM64=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name=="wave-macos-arm64") | .browser_download_url')
          URL_X86_64=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name=="wave-macos-x86_64") | .browser_download_url')
          URL_LINUX=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name=="wave-linux-x86_64") | .browser_download_url')
          SHA256_ARM64=$(curl -L "$URL_ARM64" | shasum -a 256 | awk '{print $1}')
          SHA256_X86_64=$(curl -L "$URL_X86_64" | shasum -a 256 | awk '{print $1}')
          SHA256_LINUX=$(curl -L "$URL_LINUX" | shasum -a 256 | awk '{print $1}')
          VERSION=$(echo "$RELEASE_JSON" | jq -r '.tag_name' | sed 's/^v//')
          echo "url_arm64=$URL_ARM64" >> $GITHUB_OUTPUT
          echo "sha256_arm64=$SHA256_ARM64" >> $GITHUB_OUTPUT
          echo "url_x86_64=$URL_X86_64" >> $GITHUB_OUTPUT
          echo "sha256_x86_64=$SHA256_X86_64" >> $GITHUB_OUTPUT
          echo "url_linux=$URL_LINUX" >> $GITHUB_OUTPUT
          echo "sha256_linux=$SHA256_LINUX" >> $GITHUB_OUTPUT
          # Debug output
          echo "Computed hashes:"
          echo "ARM64: $SHA256_ARM64"
          echo "X86_64: $SHA256_X86_64"
          echo "LINUX: $SHA256_LINUX"
      - name: Update formula
        run: |
          # Update URLs to point to new version
          sed -i "s|releases/download/v[^/]*/wave-macos-arm64|releases/download/v${{ steps.get_release.outputs.version }}/wave-macos-arm64|g" Formula/wave.rb
          sed -i "s|releases/download/v[^/]*/wave-macos-x86_64|releases/download/v${{ steps.get_release.outputs.version }}/wave-macos-x86_64|g" Formula/wave.rb
          sed -i "s|releases/download/v[^/]*/wave-linux-x86_64|releases/download/v${{ steps.get_release.outputs.version }}/wave-linux-x86_64|g" Formula/wave.rb
          
          # Update version
          sed -i 's/version "[^"]*"/version "${{ steps.get_release.outputs.version }}"/' Formula/wave.rb
          
          # Update SHA256 hashes by finding the line after each platform's URL and replacing the entire sha256 line
          # Use awk for more reliable multiline replacement
          awk -v arm64_sha="${{ steps.get_release.outputs.sha256_arm64 }}" \
              -v x86_64_sha="${{ steps.get_release.outputs.sha256_x86_64 }}" \
              -v linux_sha="${{ steps.get_release.outputs.sha256_linux }}" '
          BEGIN { in_arm = 0; in_intel = 0; in_linux = 0 }
          /on_arm/ { in_arm = 1; in_intel = 0; in_linux = 0 }
          /on_intel/ { in_arm = 0; in_intel = 1; in_linux = 0 }
          /on_linux/ { in_arm = 0; in_intel = 0; in_linux = 1 }
          /^  end$/ { in_arm = 0; in_intel = 0; in_linux = 0 }
          /sha256/ {
            if (in_arm) {
              print "      sha256 \"" arm64_sha "\""
            } else if (in_intel) {
              print "      sha256 \"" x86_64_sha "\""
            } else if (in_linux) {
              print "      sha256 \"" linux_sha "\""
            } else {
              print $0
            }
            next
          }
          { print }
          ' Formula/wave.rb > Formula/wave.rb.tmp && mv Formula/wave.rb.tmp Formula/wave.rb
          
          # Show the updated formula for debugging
          echo "Updated formula:"
          cat Formula/wave.rb
      - name: Check if changes were made
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes needed"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git diff
          fi
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |-
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Formula/wave.rb
          git commit -m "Update wave formula to ${{ steps.get_release.outputs.version }}"
          git push origin HEAD:main
